replicaCount: 1

image: 
  repository: yemrad/backend
  pullPolicy: IfNotPresent


service:
  type: NodePort
  port: 5555
  name: backend
  targetport: 5555
  nodePort: 32000

container:
  name: backend

cpa: 
 podAntiAffinity:         
 requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    -  {{ .Release.Name }} 
                topologyKey: kubernetes.io/hostname