apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend
  namespace: ms
  labels:
    app:  backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  backend
    spec:
      containers:
      - name:  backend
        image:  yemrad/backend
        ports:
        - containerPort:  5555
          name:  backend
---


apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ms
spec:
  selector:
    app: backend
  type: NodePort
  ports:
  - name: backend
    protocol: TCP
    port: 5555
    targetPort: 5555
    nodePort: 30001
---
