apiVersion: apps/v1
kind: Deployment
metadata:
  name:  clients
  namespace: ms
  labels:
    app:  clients
spec:
  selector:
    matchLabels:
      app: clients
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  clients
    spec:
      containers:
      - name:  clients
        image:  yemrad/client
        ports:  3000
      - containerPort:  3000
         name:  clients
---


apiVersion: v1
kind: Service
metadata:
  name: clients
  namespace: ms
spec:
  selector:
    app: clients
  type: NodePort
  ports:
  - name: myjob
    port: 3000
    targetPort: 3000
    nodePort: 30002
---
