apiVersion: apps/v1
kind: Deployment
metadata:
    name: clients
  labels:
   {{- include "helm-charts.labels" . |
    nindent 4 }}
spec:
  selector:
    matchLabels:
   {{- include "helm-charts.selectorLabels" . |
    nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
   {{- include "helm-charts.selectorLabels" . |
    nindent 8 }}
    spec:
      containers:
      - name:  {{ .Values.container.name }}
        image:  {{ .Values.image.repository | quote }}
        imagePullPolicy:  {{ .Values.image.pullPolicy }}
        ports:
        - containerPort:  {{ .Values.service.port }}
          name:  {{ .Values.container.name }}
          targetPort:  {{ .Values.service.targetport }}
     